name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: 'mukesh2055singh@gmail.com'
        password: 'Patel@606890'

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: mukesh2055singh/deployment_repo

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t mukesh2055singh/deployment_repo.

    - name: Push Docker image to Docker Hub
